### ISSUE TITLE
无法查看数据库与数据

### ISSUE THREAD

**Issue by synhi** [pikadun/vscode-redis#6]
![image](https://user-images.githubusercontent.com/12025422/85203587-652e4a00-b341-11ea-8ea1-f6094ae55ff8.png)

**Comment by synhi** [comment]
命令行可以正常使用

**Comment by pikadun** [comment]
你好，我这暂时无法重现你说的问题。
可以提供一下vscode版本号，redis版本号吗？
目前这个扩展的功能也不是很完善，还没加入日志功能，暂时没法定位到问题，很尴尬😅

**Comment by pikadun** [comment]
目前一个定位的办法就是把代码拉到本地，用vscode启动一下看看哪里出了问题。
下一个版本我会加入应用程序日志来收集错误信息。

**Comment by synhi** [comment]
可能是我的 redis 版本问题，今天用的虚拟机 centos 系统 redis5.0 可以正常显示，
出错的是 windows 版 redis 3.2
vscode 是 1.46.1 64位便携版

**Comment by pikadun** [comment]
非常感谢！
我一直没有测试windows版本的redis是否可用。

**Comment by pikadun** [comment]
@ShynHan  左侧树视图中使用  `CONFIG GET DATABASES` 命令获取数据库列表，但是windows的redis3.2版本只能使用 `CONFIG GET databases` 命令获取，这是个兼容性的问题，谢谢反馈。
